baseURL = 'https://ajbrown.au/'
languageCode = 'en-au'
title = "Andrew Brown"
author = "Me"
copyright = "© Andrew Brown"

theme = 'risotto'


[params.theme]
palette = "base16-toothpaste"

[params.about]
title = "Andrew Brown..."
description = """...is a 4th-year Computer Science student.

He has been described as \"The dad from a picturesque Disney family, but like, from the start of the movie before the wife dies.\""""

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/andrewj-brown"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:me@ajbrown.au"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Thoughts"
    url = "/thoughts/"
    weight = 9
  [[menu.main]]
    identifier = "playlist"
    name = "Playlist"
    url = "/playlist/"
    weight = 11

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  
    [markup.tableOfContents]
      startLevel = 2
      endLevel = 3
      ordered = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
